const TRIVIA_QUESTIONS = [
    {"category":"Camp", "q":"How many miles will the camp buses travel to and from camp this summer? (Rockbridge 2x, SharpTop Cove, CrossRoads)", "a":"3148 miles"},
    {"category":"Art", "q":"Michelangelo’s marble sculpture of David is in what city?", "a":"Florence, Italy"},
    {"category":"Movies", "q":"What is the name of the kleptomaniac monkey in Disney’s Aladdin?", "a":"Abu"},
    {"category":"Bible", "q":"On which mountain did Moses receive the Ten Commandments?", "a":"Mount Sinai"},
    {"category":"Technology", "q":"The dollar sign appears above which number on a computer keyboard?", "a":"4"},
    {"category":"Food", "q":"Sriracha is a type of hot sauce named after a city located in what country?", "a":"Thailand"},
    {"category":"Books", "q":"Who did Lucy first meet after stepping through the wardrobe into Narnia?", "a":"Mr. Tumnus"},
    {"category":"Music", "q":"Who performed at this year's Superbowl halftime show?", "a":"Justin Timberlake"},
    {"category":"Sports", "q":"Who is the all time leading point scorer in NBA history?", "a":"Kareem Abdul-Jabbar"},
    {"category":"Chemistry", "q":"Name the chemical element with the symbol 'K'.", "a":"Potassium"},
    {"category":"World History", "q":"When did the Cold War end?", "a":"1989 or 1991"},
    {"category":"Entertainment", "q":"What is the name of the current bachelor on the show 'The Bachelor'?", "a":"Arie Luyendyk Jr."},
    {"category":"Home Improvement", "q":"What are the height and width of a 2 x 4?", "a":"1 1/2 in x 3 1/2 in"},
    {"category":"Medicine", "q":"The first type of aspirin, pain killer and fever reducer came from the bark of what tree?", "a":"The willow tree"},
    {"category":"Theater", "q":"What Broadway production was nominated for sixteen Tony awards in 2016?", "a":"Hamilton"},
    {"category":"Music", "q":"Who wrote the popular Easter hymn “Christ the Lord is Risen Today”?", "a":"Charles Wesley"},
    {"category":"Geography", "q":"Name the world's biggest island.", "a":"Greenland"},
    {"category":"Books", "q":"What class did Neville teach at Hogwarts as an adult?", "a":"Herbology"},
    {"category":"Sports", "q":"In the Tour de France what color jersey is worn by the cyclist with the fastest time?", "a":"Yellow"},
    {"category":"Politics", "q":"Former Governor of California, Arnold Schwarzenegger, was born in which country?", "a":"Austria"},
    {"category":"Games", "q":"How many squares are there on a standard chess board?", "a":"64"},
    {"category":"Entertainment", "q":"Who played the role of Jesus in NBC's edition of Jesus Christ Superstar?", "a":"John Legend"},
    {"category":"Pop Culture", "q":"What is the name of Prince Harry's fiance?", "a":"Meghan Markle"},
    {"category":"Movies", "q":"In what year was the first Star Wars movie released?", "a":"1977"},
    {"category":"Sports", "q":"Who was FC Cincinnati’s leading scorer in the 2017 season, with 12 goals and 3 assists?", "a":"Djiby Fall"},
    {"category":"Technology", "q":"IBM is a multinational technology company, what do the initials IBM stand for?", "a":"International Business Machines"},
    {"category":"Music", "q":"Beyoncé was a member of which group before going solo?", "a":"Destiny’s Child"},
    {"category":"US History", "q":"How many U.S. presidents have no siblings?", "a":"None"},
    {"category":"Games", "q":"What was the first video game that allowed the game to be saved?", "a":"The Legend of Zelda"},
    {"category":"Chemistry", "q":"Brass is an alloy made of what two metals?", "a":"Copper and Zinc"},
    {"category":"Entertainment", "q":"What did Kim Kardashian name her third baby?", "a":"Chicago"},
    {"category":"US History", "q":"Which President is on the United States 1,000 dollar bill?", "a":"Grover Cleveland"},
    {"category":"Contact Work", "q":"What is the name of the drink in at the Asian grocery store?", "a":"Milk Drink"},
    {"category":"WyldLife Weekend", "q":"How many kids did we take to WyldLife Weekend?", "a":"20"},
    {"category":"Sports Star", "q":"What is the farthest Jaden has traveled to play rugby?", "a":"Las Vegas, NV"},
    {"category":"YL Growth", "q":"Name ALL 9 schools that have Urban clubs.", "a":"West High, Dater, Walnut Hills, Clark, Hughes, Withrow, Newport, Holmes, Norwood"},
    {"category":"Camp Spots", "q":"How many kids will we take to camp this summer?", "a":"142"},
];